dist: xenial   # required for Python >= 3.7
language: python
python:
   - 2.7
   - 3.6
   - 3.7

install:
   - pip install -r requirements.txt
   - pip install .

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
   - pytest
   - make full-demo
